FROM node:18-alpine


WORKDIR /app

COPY frontend/package*.json app/
RUN npm install

# Copy all frontend source code
COPY frontend/ app/

# Expose default React dev server port
EXPOSE 3000

# Run React dev server
CMD ["npm", "run", "dev"]
