site_name: ConTrade Documentation
nav:
  - Home: index.md
  - CLI: CLI.md
  - Configuration Files: CONFIG.md
  - .env Configuration: ENV.md
  - Runtime Error Codes: ERRORS.md
  - Architecture: ARCHITECTURE.md
  - Tech Stack: TECHSTACK.md
  - Change Log: CHANGELOG.md
  - Todo/Upcoming Features: TODO.md

docs_dir: docs

theme:
  name: material