FROM python:3.12-slim

WORKDIR /app

# Install Python side requirements
COPY requirements.txt . 
RUN pip install -r requirements.txt

COPY . /app/

# Build, Train, and Dump Model
RUN python3 -m src.ml.pipeline

# Serialized ML Model
COPY src/ml/models/decider/model.pkl src/ml/models/decider/model.pkl

# Expose the server port (default is 5000 for flask)
EXPOSE 5000

# Start server  
CMD ["python3", "-m", "src.api.internal.model_api.model_api"]
