name: Go Tests

on: [push, pull_request]

jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Install TA-Lib from source
        run: |
          curl -L -o ta-lib-0.6.4-src.tar.gz https://github.com/ta-lib/ta-lib/releases/download/v0.6.4/ta-lib-0.6.4-src.tar.gz
          tar -xzf ta-lib-0.6.4-src.tar.gz
          cd ta-lib-0.6.4/
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Run Go Tests
        run: |
          cd src/runtime/go-src/
          go mod tidy
          go test ./...