name: Python Tests

on: [push, pull_request]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'

      - name: Install TA-Lib from source
        run: |
          curl -L -o ta-lib-0.4.0-src.tar.gz http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Install TA-lib
        run: |
          python3 -m pip install TA-Lib

      - name: Install all other dependencies
        run: pip install -r requirements.txt

      - name: Python Tests
        run: PYTHONPATH=. pytest